.pre-commit-config.yaml, README.md, marray/__init__.py, marray/tests/test_marray.py, pyproject.toml
This adds a couple of `pre-commit` hooks:
- `trailing-whitespace`, `end-of-file-fixer`, `check-docstring-first`: basic hooks
- `ruff`: linting
- `prettier`: format config files (mostly yaml)
- `taplo`: format toml
- `validate-pyproject`: validate `pyproject.toml`'s project table
=> configure `pre-commit`

marray/__init__.py, pyproject.toml
Closes gh-2.
~~Uses hack to eliminate NumPy dependency.~~ Let's keep gh-5 on the table, though.
=> MAINT: remove NumPy dependency

marray/__init__.py, marray/tests/test_marray.py
One thing that came up here - should `empty_like`, `full_like`, `ones_like`, and `zeros_like` preserve the mask of the input array?
Otherwise, the behavior for most array creation functions, which do not accept an array as input, is to create a masked array with an all-false mask. The exceptions are `tril`, `triu`, and `meshgrid`, for which I assume the desired behavior is to apply the function to the data and mask separately and create a new masked array from the result.
=> TST: test/fix array creation functions

marray/__init__.py, marray/tests/test_marray.py
Grouping these two because because it was convenient to do so. Pretty straightforward.
=> TST: test/fix `astype`/`clip`

marray/__init__.py, marray/tests/test_marray.py
Also remove `xp_take_along_axis` and `xp_swapaxes`, which aren't needed here. `take_along_axis` will be in the next version of the standard anyway, which will make it much easier to implement.
=> TST: test sorting functions

marray/__init__.py, marray/tests/test_marray.py
See gh-24 for issue about using a masked array as an index. For now, we don't test the behavior, really, except by explictly converting a 0-D masked array to an index.
For the dlpack methods:
- I think `__dlpack_device__` is what we want, and the simple test is probably fine, but this brings to mind that we might want to require `assert data.device == mask.device`.
- There are currently a lot of issues with DLPack (e.g. see gh-21890 for some information and links), so I don't think it's a big problem if we don't have a proper implementation of `__dlpack__` or good test of `todevice` right now. Opened gh-25 as a reminder.
=> TST: test scalar conversions, indexing, and dlpack methods

marray/__init__.py, marray/tests/test_marray.py
Currently, the `marrray` package contains exactly one thing: the `masked_array` function. (gh-17 suggests renaming `masked_array` to `get_marray`, which would make some of the code below a bit more readable.)
This PR makes `masked_array` return a real Python module, whereas before it was just a generic `object` with attributes.
Now, when executed as a script, this works:
```python3
import numpy as xp
import marray
mxp = marray.masked_array(xp)
from mxp import asarray
asarray([1, 2, 3], mask=True)
```
Currently, the name of the module `mxp` is hard-coded. This doesn't work.
```python3
mod = marray.masked_array(xp)
from mod import asarray
```
Perhaps `masked_array` could accept an argument:
```python3
mod = marray.masked_array(xp, 'mod')
from mod import asarray
```
This is something we can …
=> ENH: make `masked_array` function return a proper module

marray/tests/test_marray.py, pyproject.toml
We're getting a ton of warnings in CI that I'm not seeing locally:
<details>
```shell
=============================== warnings summary ===============================
marray/tests/test_marray.py::test_elementwise_unary[array_api_strict-bool-logical_not]
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/array_api_strict/_elementwise_functions.py:711: UserWarning: You are comparing a array_api_strict dtype against a NumPy native dtype object, but you probably don't want to do this. array_api_strict dtype objects compare unequal to their NumPy equivalents. Such cross-library comparison is not supported by the standard.
if x.dtype not in _boolean_dtypes:
marray/tests/test_marray.py: 12 warnings
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/array_api_st …
```
=> MAINT: avoid UserWarnings

marray/__init__.py, marray/tests/test_marray.py
Closes gh-32
After this and gh-34, coverage (according to `coverage`) should be about as high as possible.
=> TST: improve coverage

marray/__init__.py
Toward gh-15.
This is not very careful to do the right thing. That's no problem, IMO. When a problem is discovered, we fix it. Much easier than predicting all possible exceptions.
Perhaps "the tutorial" can be replaced with a link when there is a tutorial.
=> DOC: forward documentation from underlying array library

marray/tests/test_marray.py
Closes gh-33
Copying ensures that the same LAPACK function is used for the matmul. This should prevent gh-33 from coming up again.
=> MAINT: copy before matmul in `test_array_binary`

marray/__init__.py, marray/tests/test_marray.py
@lucascolley re: gh-47, This should fix the `array_api_test` failures involving `mean`, `std`, and `var`.
=> MAINT: fix some array_api_test failures

marray/__init__.py, marray/tests/test_marray.py, tools/xp-tests-xfails.txt
Closes gh-34. Removes array-ai-tests skips of `unique_` functions.
As an enhancement, we could automatically promote dtypes and/or exhaustively look for another sentinel value, but this is enough to consider the set functions to be implemented.
=> MAINT: unique_: correct and test set functions

README.md, marray/__init__.py, marray/tests/test_marray.py, mybook/intro.md, mybook/tutorial.md, tools/xp-tests.patch
Closes gh-59
@lucascolley I think this is what you had in mind for gh-59
```python3
import numpy as np
import array_api_strict as xp
import marray
mnp = marray.get_namespace(np)
mxp = marray.get_namespace(xp)
xp1 = mnp.arange(2).__array_namespace__()
xp1.__name__  # 'mxp(numpy)'
xp1.arange(2).data.__array_namespace__().__name__  # 'numpy'
xp2 = mxp.arange(3).__array_namespace__()
xp2.__name__  # 'mxp(array_api_strict)'
xp2.arange(3).data.__array_namespace__().__name__  # 'array_api_strict'
```
A problem is that this no longer works:
```
from mnp import asarray
from mxp(numpy) import asarray
```
I don't think we can tell the name that the user assigns the namespace to, and I don't think we can have parentheses in the name we want to be able to import from. I can think of a few ways to …
=> ENH: modify namespace based on backend

marray/__init__.py, marray/tests/test_marray.py
Should fix some failures in gh-71.
Also closes gh-72.
=> MAINT: fix indexing with tuples

README.md
This should fix gh-75 following the advice of oscal-compass/compliance-trestle#1628.
=> Fix logo URL; eliminate footnote

marray/__init__.py, marray/tests/test_marray.py
`take_along_axis` is defined in the draft standard. I'll go ahead and add it now for use in scipy/scipy#22352.
=> ENH: add take_along_axis

marray/__init__.py
I want to release again with `take_along_axis` to more easily investigate use of `marray` in https://github.com/scipy/scipy/pull/22352.
=> Update version to 0.0.7

marray/__init__.py
=> MAINT: be more careful to only access `data` attribute of masked arrays

marray/__init__.py
gh-81 is important to scipy/scipy#22393.
=> Update version to 0.0.8

marray/__init__.py
Matmul was very slow before!
```python3
import numpy as np
from marray import numpy as mnp
rng = np.random.default_rng(893458972872134)
shape = (1000, 1000)
data_a = rng.random(shape)
mask_a = rng.random(shape) > 0.5
data_b = rng.random(shape)
mask_b = rng.random(shape) > 0.5
xa = mnp.asarray(data_a.copy(), mask=mask_a.copy())
xb = mnp.asarray(data_b.copy(), mask=mask_b.copy())
ya = np.ma.masked_array(data_a.copy(), mask=mask_a.copy())
yb = np.ma.masked_array(data_b.copy(), mask=mask_b.copy())
```
Still not as fast as NumPy masked array, but that might take a little more work. Let's start with this and improve further once gh-85 is ready.
=> MAINT: speed up array binary operations

marray/tests/test_marray.py
Improves pytest output and make progress toward benchmarking by ensuring that `lambda`s have string names associated with them.
Now, the pytest output shows, e.g. 
```
test_marray.py::test_arithmetic_unary[numpy-uint8-+x-<lambda>] 
test_marray.py::test_arithmetic_unary[numpy-uint8--x-<lambda>] 
test_marray.py::test_arithmetic_unary[numpy-uint8-abs-abs] 
test_marray.py::test_arithmetic_unary[numpy-uint8-x.__abs__-<lambda>] 
test_marray.py::test_arithmetic_unary[numpy-uint8-x.__neg__-<lambda>] 
test_marray.py::test_arithmetic_unary[numpy-uint8-x.__pos__-<lambda>] 
```
whereas before it was like:
```
test_marray.py::test_arithmetic_unary[numpy-uint8-<lambda>0] 
test_marray.py::test_arithmetic_unary[numpy-uint8-<lambda>1] 
test_marray.py::test_arithmetic_unary[numpy-uint8-<lambda>2] …
```
=> TST: improve parametrization style

marray/__init__.py, marray/tests/test_marray.py, pixi.lock, pyproject.toml
Closes gh-99. 
Closes gh-82.
When this is ready:
- ~~I'll `try` imports in the test file, and if an import fails, the backend won't be added to the `xps` list.~~ Done.
- ~~To get PyTorch running in CI, think I'll just need to add `pytorch` (and I guess `array-api-compat`, if it's not already there) to the test dependencies in `pyproject.toml`, then `pixi update`. Does that sound right @lucascolley?~~ Done.
- ~~I don't think I want to spend money running on the GPU. I can do CuPy locally. How do we indicate that CuPy is an optional test dependency for users but that Pixi doesn't need to try installing it in CI?~~ Follow-up PR.
=> TST: run tests with PyTorch

marray/__init__.py
Masked values should not affect the length of the string representation of characters in an array, so set them all to False/zero before taking `str` or `repr`.
=> MAINT: minor str/repr improvement

marray/__init__.py, marray/tests/test_marray.py
Toward gh-25.
Not extensively tested. This doesn't close _ gh-25; we can improve later.
=> MAINT: allow use of 'device' in asarray

marray/__init__.py, marray/tests/test_marray.py
~~This should probably wait to merge until after gh-110 (so we can test with PyTorch).~~ Done.
In the meantime, a question is whether array type in = array type out should apply here. The return value of `count` never has masked elements. It is essentially a generalization of `shape[axis]`, which returns a scalar, not an array. 
In SciPy, this is used like:
https://github.com/scipy/scipy/blob/25ca572f6dcaf2d7ad38d96fdc9def33b2f8a385/scipy/stats/_stats_py.py#L1244-L1250
so it works fine returning an `xp` array, not an `mxp` array. I imagine that it could just as well return `mxp` arrays.
Thoughts?
=> MAINT/TST: count: improve implementation, test

marray/__init__.py, marray/tests/test_marray.py
This implements "Option 4" from gh-24 regarding masked boolean indices.
`__getitem__` returns elements from `self` for each element of `key` that is True OR masked. Elements are masked wherever either `self` or `key` were masked.
`__setitem__` sets elements of `self` for each element of `key` that is True OR masked. Elements are masked wherever either `other` or `key` were masked.
```python3
import numpy as np
from marray import numpy as mxp
x_val = np.arange(8)
x_mask = [False, False, False, False, True, True, True, True]
i_val = [False, False, True, True, False, False, True, True]
i_mask = [False, True, False, True, False, True, False, True]
x = mxp.asarray(x_val, mask=x_mask)
i = mxp.asarray(i_val, mask=i_mask)
x = mxp.asarray(x_val, mask=x_mask)
other = 9
x             # [0 1 2 3 _ _ …
```
=> MAINT: __getitem__/__setitem__: define behavior for boolean index with masked elements

marray/__init__.py, marray/tests/test_marray.py
This closes gh-123 and re-opens the `__setitem__` part of gh-108; the logic just wasn't correct for array right hand sides.
=> Revert __setitem__ changes of gh-108 and increment version number

marray/__init__.py, mybook/tutorial.md
Now, when doing e.g.:
```python3
from marray import torch as mxp
```
actually import `torch` from `array_api_compat`, since it really doesn't work otherwise.
The latest version of CuPy might not need this treatment, but I've added it anyway. I'll test it shortly.
If this optional dependency should be noted in `pyproject.toml` or such, please commit here or open a separate PR.
=> ENH: automatically import some modules from `array_api_compat`

marray/__init__.py, marray/tests/test_marray.py
Updates to address failures with array-api-strict 2.4. ~~Should allow~~ Allows un-skipping array-api-strict added by scipy/scipy#23381 (confirmed locally).
Note: https://github.com/data-apis/array-api-strict/pull/145#issuecomment-3148732475
~~Also should investigate why torch meshgrid test is failing now if it wasn't before.~~ data-apis/array-api-compat#340
=> MAINT: updates to fix errors in array-api-strict 2.4

marray/__init__.py, marray/tests/test_marray.py, pixi.lock
In pydata/xarray#10574 I mentioned that a particular method raises an error about not being able to `pickle` the array namespace. As it turns out, this is raised by the default implementation of `object.__deepcopy__`, so by overriding that module to do the same as `xp.asarray(x, copy=True)` we can avoid that error.
Another option would be to deep-copy the data and mask and create a new object from it, but that may not be worth the effort.
(As an aside, I just noticed that when calling `mxp.asarray([1, 2, 3], copy=True)` we create an array of masked values and immediately copy it, which may be wasteful)
=> implement `__deepcopy__` for `MArray`

marray/__init__.py, marray/tests/test_marray.py
Fixes the test failures observed in gh-136.
~~Looks like we need our own test of `take`. If [`np.ma.take`](https://numpy.org/doc/stable/reference/generated/numpy.ma.masked_array.take.html) implementation agrees reasonably well with the array API standard, it shouldn't be too hard.~~ *Done*.
=> MAINT: fix `array-api-strict` test failures
